#!/usr/bin/env bash
set -e # halt script on error

bundle install -j8 > /dev/null || bundle install > /dev/null
python3 ./script/tag_generator.py
bundle exec jekyll build --trace
bundle exec htmlproofer --assume-extension ./_site --allow-hash-href --external_only --http-status-ignore "0, 302, 400, 401, 403, 999" ./out